services:
  - type: worker
    env: node
    name: github-issues-to-slack
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: GITHUB_REPOSITORY
        sync: false
